version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "requests"

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-minor"]
